Update build_kernel.yml
- add multi arch compatibility

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -7,13 +7,14 @@ on:
       kernel_version:
         description: 'Kernel Version'
         required: true
-        default: '6.14.11'
+        default: '6.18.16'
         type: string
 
 jobs:
   build_kernel:
     runs-on: self-hosted
-    environment: build
+    permissions:
+      contents: write
 
     steps:
     - name: Checkout repository
@@ -22,9 +23,9 @@ jobs:
         fetch-depth: 1
 
     - name: Install dependencies
-      run: apt-get update && apt-get -y install build-essential flex bison libncurses-dev libssl-dev libelf-dev bc dwarves kmod squashfs-tools rsync git cpio xz-utils iucode-tool
+      run: apt-get update && apt-get -y install aarch64-linux-gnu-gcc build-essential flex bison libncurses-dev libssl-dev libelf-dev bc dwarves kmod squashfs-tools rsync git cpio xz-utils iucode-tool
 
-    - name: Compile Kernel
+    - name: Compile Kernel for amd64
       run: |
         # Set Variables and create directories
         WORK_DIR=${{ github.workspace }}
@@ -58,7 +59,7 @@ jobs:
 
         # Save Kernel
         echo "Creating Kernel archive..."
-        XZ_OPT="-9 -T0" tar -cJf $WORK_DIR/${KERNEL_V}-mos.tar.xz .
+        XZ_OPT="-9 -T0" tar -cJf $WORK_DIR/${KERNEL_V}-mos_amd64.tar.xz .
 
         # Install Modules to /lib/modules
         make modules_install -j$(nproc --all)
@@ -130,20 +131,108 @@ jobs:
         md5sum $WORK_DIR/image | awk '{print $1}' > $WORK_DIR/image.md5
         md5sum $WORK_DIR/drivers | awk '{print $1}' > $WORK_DIR/drivers.md5
         md5sum $WORK_DIR/microcode | awk '{print $1}' > $WORK_DIR/microcode.md5
-        md5sum $WORK_DIR/${KERNEL_V}-mos.tar.xz | awk '{print $1}' > $WORK_DIR/${KERNEL_V}-mos.tar.xz.md5
+        md5sum $WORK_DIR/${KERNEL_V}-mos_amd64.tar.xz | awk '{print $1}' > $WORK_DIR/${KERNEL_V}-mos_amd64.tar.xz.md5
 
         echo "FW_COMMIT=$FW_COMMIT
         FW_COMMIT_SHORT=$FW_COMMIT_SHORT
         INTEL_MICROCODE=$INTEL_MICROCODE" >> $GITHUB_ENV
 
-    - name: Create Release
-      id: create_release
-      uses: actions/create-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Compile Kernel for arm64
+      run: |
+        # Set Variables and create directories
+        WORK_DIR=${{ github.workspace }}
+        BUILD_DIR=${WORK_DIR}/build
+        KERNEL_V=${{ github.event.inputs.kernel_version }}
+        rm -rf $WORK_DIR/$KERNEL_V $BUILD_DIR /lib/modules /lib/firmware
+        mkdir -p $BUILD_DIR $WORK_DIR/$KERNEL_V $BUILD_DIR/$KERNEL_V /lib/modules /lib/firmware
+
+        # Safety check for Kernel versions ending with 0
+        if [ "${KERNEL_V##*.}" == "0" ]; then
+          DL_KERNEL_V="${KERNEL_V%.*}"
+        else
+          DL_KERNEL_V=$KERNEL_V
+        fi
+
+        # Extract Kernel
+        cd $BUILD_DIR
+        tar -C $BUILD_DIR/$KERNEL_V --strip-components=1 -xf $BUILD_DIR/linux-$KERNEL_V.tar.xz
+
+        # Copy Kernel config
+        cd $BUILD_DIR/$KERNEL_V
+        cp $WORK_DIR/kernel-config/config_arm $BUILD_DIR/$KERNEL_V/.config
+
+        # Compile Kernel
+        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig
+        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc --all)
+
+        # Copy image to output directory
+        cp $BUILD_DIR/$KERNEL_V/arch/arm64/boot/Image $WORK_DIR/image_arm
+
+        # Save Kernel
+        echo "Creating Kernel archive..."
+        XZ_OPT="-9 -T0" tar -cJf $WORK_DIR/${KERNEL_V}-mos_arm64.tar.xz .
+
+        # Install Modules to /lib/modules
+        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc --all) modules_install
+
+        # Remove old firmware files
+        cd $WORK_DIR
+        rm -rf $WORK_DIR/required_firmware $WORK_DIR/required_firmware_complete
+
+        # Set MODULE_PATH variable
+        cd $WORK_DIR
+        MODULE_PATH="/lib/modules/${KERNEL_V}-mos"
+
+        # Generate file list
+        find "$MODULE_PATH" -name "*.ko*" -exec modinfo {} \; 2>/dev/null | \
+          grep "^firmware:" | cut -d: -f2- | sed 's/^[[:space:]]*//' | sort -u \
+          > "$WORK_DIR/required_firmware"
+
+        # Make sure to copy all files including symlinks
+        while read fw; do
+          full="$WORK_DIR/linux-firmware/$fw"
+          if [ -L "$full" ]; then
+            echo "$fw" >> "$WORK_DIR/required_firmware_complete"
+            target=$(readlink -f "$full")
+            rel="${target#$WORK_DIR/linux-firmware/}"
+            echo "$rel" >> "$WORK_DIR/required_firmware_complete"
+          elif [ -f "$full" ]; then
+            echo "$fw" >> "$WORK_DIR/required_firmware_complete"
+          else
+            echo "Missing Firmware: $fw" >&2
+          fi
+        done < "$WORK_DIR/required_firmware"
+
+        # Remove duplicates
+        sort -u -o "$WORK_DIR/required_firmware_complete" "$WORK_DIR/required_firmware_complete"
+
+        # Copy firmware files
+        rsync -av --files-from="$WORK_DIR/required_firmware_complete" "$WORK_DIR/linux-firmware/" /lib/firmware/
+
+        # Copy over Modules and Firmware files and make sure to save attributes
+        cp -a /lib/modules $WORK_DIR/$KERNEL_V/
+        cp -a /lib/firmware $WORK_DIR/$KERNEL_V/
+        rm -rf $WORK_DIR/$KERNEL_V/lib/modules/${KERNEL_V}-mos/build
+        cd $WORK_DIR/$KERNEL_V
+
+        # Copy licenses and copying to drivers
+        mkdir -p $WORK_DIR/$KERNEL_V/usr/share/doc/linux/LICENSES/preferred
+        cp $BUILD_DIR/$KERNEL_V/COPYING $WORK_DIR/$KERNEL_V/usr/share/doc/linux/COPYING
+        cp $BUILD_DIR/$KERNEL_V/LICENSES/preferred/* $WORK_DIR/$KERNEL_V/usr/share/doc/linux/LICENSES/preferred/
+
+        # Create drivers image
+        mksquashfs $WORK_DIR/$KERNEL_V $WORK_DIR/drivers_arm64 -noappend -comp xz
+
+        # Create md5 sums
+        md5sum $WORK_DIR/image_arm64 | awk '{print $1}' > $WORK_DIR/image_arm64.md5
+        md5sum $WORK_DIR/drivers_arm64 | awk '{print $1}' > $WORK_DIR/driversarm64.md5
+        md5sum $WORK_DIR/${KERNEL_V}-mos_arm64.tar.xz | awk '{print $1}' > $WORK_DIR/${KERNEL_V}-mos_arm64.tar.xz.md5
+
+    - name: Create and Upload Release
+      uses: softprops/action-gh-release@v2
       with:
         tag_name: ${{ github.event.inputs.kernel_version }}-mos
-        release_name: "${{ github.event.inputs.kernel_version }}-mos"
+        name: "${{ github.event.inputs.kernel_version }}-mos"
         body: |
           Custom MOS Kernel and Drivers: ${{ github.event.inputs.kernel_version }}-mos
 
@@ -154,88 +243,15 @@ jobs:
           Microcode:
           [AMD](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amd-ucode?id=${{ env.FW_COMMIT }}): ${{ env.FW_COMMIT_SHORT }}
           [Intel](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/${{ env.INTEL_MICROCODE }}): ${{ env.INTEL_MICROCODE }}
-        draft: false
-        prerelease: false
-
-    - name: Upload Kernel to Release
-      uses: actions/upload-release-asset@v1
+        files: |
+          ${{ github.workspace }}/image*
+          ${{ github.workspace }}/drivers*
+          ${{ github.workspace }}/microcode*
+          ${{ github.workspace }}/${{ github.event.inputs.kernel_version }}-mos*
+        overwrite_files: true
+        fail_on_unmatched_files: false
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/image
-        asset_name: image
-        asset_content_type: application/vnd.debian.binary-package
-
-    - name: Upload md5 to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/image.md5
-        asset_name: image.md5
-        asset_content_type: text/plain
-
-    - name: Upload Drivers to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/drivers
-        asset_name: drivers
-        asset_content_type: application/vnd.debian.binary-package
-
-    - name: Upload Drivers md5 to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/drivers.md5
-        asset_name: drivers.md5
-        asset_content_type: text/plain
-
-    - name: Upload Microcode to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/microcode
-        asset_name: microcode
-        asset_content_type: application/vnd.debian.binary-package
-
-    - name: Upload Microcode md5 to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/microcode.md5
-        asset_name: microcode.md5
-        asset_content_type: text/plain
-
-    - name: Upload Kernel to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/${{ github.event.inputs.kernel_version }}-mos.tar.xz
-        asset_name: ${{ github.event.inputs.kernel_version }}-mos.tar.xz
-        asset_content_type: application/x-xz-compressed-tar
-
-    - name: Upload Kernel md5 to Release
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/${{ github.event.inputs.kernel_version }}-mos.tar.xz.md5
-        asset_name: ${{ github.event.inputs.kernel_version }}-mos.tar.xz.md5
-        asset_content_type: text/plain
 
     - name: Trigger mos-addon-drivers build workflow
       if: success()
